### ISSUE TITLE
Please use a NRF version tag, not a intermediate development commit

### ISSUE THREAD

**Issue by boaks** [makerdiary/nrf9151-connectkit#1]
[west.yml](https://github.com/makerdiary/nrf9151-connectkit/blob/main/west.yml#L20) imports NRF from a development commit. Please use version tags, if possible.

Current:

```
  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: 98a5e50b9ac142ae2114f0b4ea257823cbf2c978
      import: true
```

FMPOV better:

```
  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v2.9.1
      import: true
```
